["/bin/bash" "/entrypoint.sh"]
file:0301efffd83b2965f98b2ef1afc7818bd8052d87fd6cb739e386ee68d6cb4dc3 in /entrypoint.sh
/home/container
update-locale lang=en_US.UTF-8 && dpkg-reconfigure --frontend noninteractive locales
apt install -y gcc g++ libgcc1 lib32gcc1 libc++-dev gdb libc6 git wget curl tar zip unzip binutils xz-utils liblzo2-2 cabextract iproute2 net-tools netcat telnet libatomic1 libsdl1.2debian libsdl2-2.0-0 libfontconfig libicu63 icu-devtools libunwind8 libssl-dev sqlite3 libsqlite3-dev libmariadbclient-dev libduktape203 locales ffmpeg gnupg2 apt-transport-https software-properties-common ca-certificates tzdata liblua5.3 libz-dev rapidjson-dev
apt update && apt upgrade -y
USER=container HOME=/home/container
ln -s /home/container/ /nonexistent
useradd -m -d /home/container -s /bin/bash container
DEBIAN_FRONTEND=noninteractive
author=Michael Parker maintainer=parker@pterodactyl.io
["bash"]
file:c855b3c65f5ba94d548d7d2659094eeb63fbf7f8419ac8e07712c3320c38b62c in /